Добавила решение первого домашнего задания
Nigma-Ks/Homework_IV_term- pull request #1
Opened 2024-09-05 20:56 UTC by Nigma-Ks

2024-11-25 20:16 UTC, yurii-litvinov requested changes

2024-11-25 20:16 UTC, yurii-litvinov commented on Homework1/Homework1.fsproj
> +    <TargetFramework>net7.0</TargetFramework>
Для только что сданной домашки версия .NET двухлетней давности выглядит странным выбором :)

2024-11-25 20:16 UTC, yurii-litvinov commented on Homework1/Program.fs
> +        if ls = [] then -1
Не-а, хочется Option, потому что -1 для вызывающего выглядит как обычный индекс списка и его руками проверять надо (и главное, можно забыть). Так в ФП не делают, а используют систему типов, чтобы гарантировать корректность.

2024-11-25 20:16 UTC, yurii-litvinov commented on Homework1/Program.fs
> +    List.scan(fun acc _ -> acc * 2) (raiseToPower 2 n 1) [ for i in n..(m + n - 1) -> i ]
```suggestion
    List.scan (fun acc _ -> acc * 2) (raiseToPower 2 n 1) [ for i in n..(m + n - 1) -> i ]
```
Но я честно без идей, зачем тут scan

2024-11-25 20:16 UTC, yurii-litvinov commented on Homework1/Program.fs
> +    nFibonacciNumberInternal 0 1 n
Это будет не очень хорошо работать, если n отрицательное

2024-11-25 20:16 UTC, yurii-litvinov commented on Homework1/Program.fs
> +    nFactorialInternal 1 n
И это

2024-11-25 23:25 UTC, Nigma-Ks commented on Homework1/Homework1.fsproj
> +    <TargetFramework>net7.0</TargetFramework>
Visual studio для мак лучше не предлагает(

2024-11-28 10:15 UTC, yurii-litvinov commented on Homework1/Homework1.fsproj
> +    <TargetFramework>net7.0</TargetFramework>
Visual studio для мак RIP, Microsoft ещё год назад велел переходить на VSCode + DevKit

2024-11-28 10:17 UTC, yurii-litvinov approved these changes
👍

2025-08-21 12:48 UTC, merged